/// Flutter icons Details
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Details
///      fonts:
///       - asset: fonts/Details.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Details {
  Details._();

  static const _kFontFam = 'Details';
  static const String? _kFontPkg = null;

  static const IconData engine = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biodiesel = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData road = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tires = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transmission = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
